ghosts catched: 1  <>  player_catched: 1  <>  catches/catched:1 <> catches/frames:0.0013192612137203
ghosts catched: 2  <>  player_catched: 1  <>  catches/catched:2 <> catches/frames:0.002212389380531
ghosts catched: 3  <>  player_catched: 1  <>  catches/catched:3 <> catches/frames:0.0033003300330033
ghosts catched: 4  <>  player_catched: 1  <>  catches/catched:4 <> catches/frames:0.0029027576197388
ghosts catched: 5  <>  player_catched: 1  <>  catches/catched:5 <> catches/frames:0.0032808398950131
