ghosts catched: 1  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0016025641025641
ghosts catched: 2  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0023809523809524
ghosts catched: 3  <>  player_catched: 1  <>  catches/catched:3 <> catches/frames:0.0015673981191223
ghosts catched: 4  <>  player_catched: 1  <>  catches/catched:4 <> catches/frames:0.002088772845953
