the Configuration used is


ghost_genetic_on: false
ghost_fitness_on: true
ghost_target_offset_freightned_on: true
ghost_migration_on: true
ghost_selective_migration_on: false
ghost_fear_on: true
ghost_go_home_on_scatter: true
ghost_chase_feared_gene_on: true
ghost_scatter_feared_gene_on: true
ghost_target_spread: 15

pill_genetic_on: false
pill_precise_crossover_on: false
speed_boost_on: true

n_ghosts: 20
n_pills: 6
pill_time: 3
restart_pill_time: 3
ghost_chase_time: 12
ghost_scatter_time: 7
ghost_respawn_time: 0
the grid is: 56 x 31
player's start grid is: 28, 18
stats_on: true
ghost_speed_max_factor: 1.1
player_speed_grid_size_factor: 5

catched
distrib_catched_target_offset[-15]: 0
distrib_catched_target_offset[-14]: 4
distrib_catched_target_offset[-13]: 7
distrib_catched_target_offset[-12]: 29
distrib_catched_target_offset[-11]: 92
distrib_catched_target_offset[-10]: 149
distrib_catched_target_offset[-9]: 45
distrib_catched_target_offset[-8]: 23
distrib_catched_target_offset[-7]: 13
distrib_catched_target_offset[-6]: 3
distrib_catched_target_offset[-5]: 6
distrib_catched_target_offset[-4]: 9
distrib_catched_target_offset[-3]: 7
distrib_catched_target_offset[-2]: 5
distrib_catched_target_offset[-1]: 9
distrib_catched_target_offset[0]: 5
distrib_catched_target_offset[1]: 5
distrib_catched_target_offset[2]: 3
distrib_catched_target_offset[3]: 2
distrib_catched_target_offset[4]: 4
distrib_catched_target_offset[5]: 4
distrib_catched_target_offset[6]: 2
distrib_catched_target_offset[7]: 5
distrib_catched_target_offset[8]: 3
distrib_catched_target_offset[9]: 7
distrib_catched_target_offset[10]: 5
distrib_catched_target_offset[11]: 6
distrib_catched_target_offset[12]: 2
distrib_catched_target_offset[13]: 2
distrib_catched_target_offset[14]: 1
distrib_catched_target_offset[15]: 2

catcher
distrib_catcher_target_offset[-15]: 0
distrib_catcher_target_offset[-14]: 3
distrib_catcher_target_offset[-13]: 0
distrib_catcher_target_offset[-12]: 3
distrib_catcher_target_offset[-11]: 3
distrib_catcher_target_offset[-10]: 11
distrib_catcher_target_offset[-9]: 2
distrib_catcher_target_offset[-8]: 1
distrib_catcher_target_offset[-7]: 1
distrib_catcher_target_offset[-6]: 0
distrib_catcher_target_offset[-5]: 0
distrib_catcher_target_offset[-4]: 0
distrib_catcher_target_offset[-3]: 0
distrib_catcher_target_offset[-2]: 2
distrib_catcher_target_offset[-1]: 0
distrib_catcher_target_offset[0]: 0
distrib_catcher_target_offset[1]: 1
distrib_catcher_target_offset[2]: 1
distrib_catcher_target_offset[3]: 0
distrib_catcher_target_offset[4]: 0
distrib_catcher_target_offset[5]: 1
distrib_catcher_target_offset[6]: 0
distrib_catcher_target_offset[7]: 0
distrib_catcher_target_offset[8]: 0
distrib_catcher_target_offset[9]: 0
distrib_catcher_target_offset[10]: 1
distrib_catcher_target_offset[11]: 2
distrib_catcher_target_offset[12]: 0
distrib_catcher_target_offset[13]: 0
distrib_catcher_target_offset[14]: 0
distrib_catcher_target_offset[15]: 1
