ghosts catched: 1  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0028985507246377
ghosts catched: 2  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0042194092827004
ghosts catched: 3  <>  player_catched: 1  <>  catches/catched:3 <> catches/frames:0.0035419126328217
ghosts catched: 4  <>  player_catched: 1  <>  catches/catched:4 <> catches/frames:0.00418410041841
