ghosts catched: 1  <>  player_catched: 1  <>  catches/catched:1 <> catches/frames:0.00055035773252614
ghosts catched: 2  <>  player_catched: 1  <>  catches/catched:2 <> catches/frames:0.0010526315789474
ghosts catched: 3  <>  player_catched: 1  <>  catches/catched:3 <> catches/frames:0.0015731515469324
ghosts catched: 4  <>  player_catched: 1  <>  catches/catched:4 <> catches/frames:0.0020833333333333
ghosts catched: 5  <>  player_catched: 1  <>  catches/catched:5 <> catches/frames:0.0025826446280992
