ghosts catched: 1  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0020366598778004
ghosts catched: 2  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0017094017094017
ghosts catched: 3  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0021337126600284
ghosts catched: 4  <>  player_catched: 0  <>  catches/catched:inf <> catches/frames:0.0019743336623889
